<?php
/**
 * Base Schema Converter
 *
 * layout.phtml
 * Defines the global layout
 *
 */
?>
<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        ?>
    </head>
    <body>
        <div id="content">
            <?php echo $this->layout()->content; ?>
            <?php echo $this->inlineScript(); ?>
        </div>
    </body>
</html>